// bookmg


CREATE TABLE `bookd` (
	`no` INT(11) NOT NULL AUTO_INCREMENT,
	`bookname` VARCHAR(50) NULL DEFAULT NULL,
	`publisher` VARCHAR(50) NULL DEFAULT NULL,
	`category` VARCHAR(50) NULL DEFAULT NULL,
	`author` VARCHAR(50) NULL DEFAULT NULL,
	`price` INT(11) NULL DEFAULT NULL,
	`borrow_yn` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`no`)
);

CREATE TABLE `borrowd` (
	`brno` INT(11) NOT NULL AUTO_INCREMENT,
	`memname` VARCHAR(50) NULL DEFAULT NULL,
	`memphone` VARCHAR(50) NULL DEFAULT NULL,
	`memprinum` VARCHAR(50) NULL DEFAULT NULL,
	`mememail` VARCHAR(50) NULL DEFAULT NULL,
	`bookname` VARCHAR(50) NULL DEFAULT NULL,
	`publisher` VARCHAR(50) NULL DEFAULT NULL,
	`category` VARCHAR(50) NULL DEFAULT NULL,
	`author` VARCHAR(50) NULL DEFAULT NULL,
	`bookno` INT(11) NULL DEFAULT NULL,
	`borrowdate` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`brno`)
);

CREATE TABLE `memberd` (
	`memNo` INT(11) NOT NULL AUTO_INCREMENT,
	`memName` VARCHAR(50) NULL DEFAULT NULL,
	`memPriNum` VARCHAR(50) NULL DEFAULT NULL,
	`memPhone` VARCHAR(50) NULL DEFAULT NULL,
	`memEmail` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`memNo`)
);
