<html>
<table>
    <thead>
        <tr>
            <td>번호</td>
            <td>제목</td>
            <td>작가</td>
            <td>장르</td>
            <td>출판사</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>01</td>
            <td>ddddd</td>
            <td>author</td>
            <td>cotegory</td>
            <td>publisher</td>
        </tr>
    </tbody>
</table>

</html>