

/* boardform*/
CREATE TABLE `boardform` (
	`boardcd` VARCHAR(20) NOT NULL,
	`boardnm` VARCHAR(40) NOT NULL,
	`UseYN` TINYINT(1) NULL DEFAULT '1',
	PRIMARY KEY (`boardcd`)
)
COLLATE='utf8_general_ci'
;
/* board*/
CREATE TABLE `board` (
	`bno` INT(11) NOT NULL AUTO_INCREMENT,
	`boardcd` VARCHAR(50) NOT NULL,
	`title` VARCHAR(200) NULL DEFAULT NULL,
	`content` MEDIUMTEXT NULL,
	`memid` VARCHAR(50) NULL DEFAULT NULL,
	`updatedt` DATE NULL DEFAULT NULL,
	`hit` INT(11) NOT NULL DEFAULT '0',
	`useYN` TINYINT(1) NULL DEFAULT '1',
	PRIMARY KEY (`bno`)
)
COLLATE='utf8_general_ci'
;

CREATE TABLE `bookd` (
	`no` INT(11) NOT NULL AUTO_INCREMENT,
	`bookname` VARCHAR(50) NULL DEFAULT NULL,
	`publisher` VARCHAR(50) NULL DEFAULT NULL,
	`category` VARCHAR(50) NULL DEFAULT NULL,
	`author` VARCHAR(50) NULL DEFAULT NULL,
	`price` INT(11) NULL DEFAULT NULL,
	`borrow_yn` TINYINT(1) NULL DEFAULT '0',
	PRIMARY KEY (`no`)
)
COLLATE='utf8_general_ci'
;

CREATE TABLE `borrowd` (
	`brno` INT(11) NOT NULL AUTO_INCREMENT,
	`memname` VARCHAR(50) NULL DEFAULT NULL,
	`memphone` VARCHAR(50) NULL DEFAULT NULL,
	`memprinum` VARCHAR(50) NULL DEFAULT NULL,
	`mememail` VARCHAR(50) NULL DEFAULT NULL,
	`bookname` VARCHAR(50) NULL DEFAULT NULL,
	`publisher` VARCHAR(50) NULL DEFAULT NULL,
	`category` VARCHAR(50) NULL DEFAULT NULL,
	`author` VARCHAR(50) NULL DEFAULT NULL,
	`bookno` INT(11) NULL DEFAULT NULL,
	`borrowdate` DATE NULL DEFAULT NULL,
	`useYN` TINYINT(1) NULL DEFAULT '1',
	PRIMARY KEY (`brno`)
)
COLLATE='utf8_general_ci'
;

CREATE TABLE `comments` (
	`commentno` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`bno` INT(11) NOT NULL,
	`memid` VARCHAR(50) NULL DEFAULT NULL,
	`memo` VARCHAR(4000) NULL DEFAULT NULL,
	`regdate` DATETIME NULL DEFAULT NULL,
	`UseYN` TINYINT(1) NULL DEFAULT '1',
	`InsertUID` VARCHAR(40) NULL DEFAULT NULL,
	`InsertDT` DATETIME NULL DEFAULT NULL,
	`UpdateUID` VARCHAR(40) NULL DEFAULT NULL,
	`UpdateDT` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`commentno`)
)
COLLATE='utf8_general_ci'
;


CREATE TABLE `memberd` (
	`memNo` INT(11) NOT NULL AUTO_INCREMENT,
	`memName` VARCHAR(50) NULL DEFAULT NULL,
	`memPriNum` VARCHAR(50) NULL DEFAULT NULL,
	`memPhone` VARCHAR(50) NULL DEFAULT NULL,
	`memEmail` VARCHAR(50) NULL DEFAULT NULL,
	`memID` VARCHAR(50) NULL DEFAULT NULL,
	`memPW` VARCHAR(50) NULL DEFAULT NULL,
	`level` INT(11) NULL DEFAULT NULL,
	`retireYN` TINYINT(1) NULL DEFAULT '1',
	PRIMARY KEY (`memNo`)
)
COLLATE='utf8_general_ci'
;